{
 "title": "ML API Dashboard-Milvus",
 "description": "Machine learning-specific metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average Semantic Similarity Latency(sec) -Milvus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(similarity_search_latency_sum{job=\"ml_api\"}[1m])) / sum (rate(similarity_search_latency_count{job=\"ml_api\"}[1m]))",
     "legendFormat": "Average Milvus Latency"
    }
   ]
  },
  {
   "title": "Standard Score (Z-Score)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(similarity_search_latency_gauge[1m])  - avg_over_time(similarity_search_latency_gauge[1w])) /  (stddev_over_time(similarity_search_latency_gauge[1w]))",
     "legendFormat": "Z-Score"
    }
   ]
  },
  {
   "title": "Standard Error of the Mean (SEM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(similarity_search_latency_gauge[1m])",
     "legendFormat": "AVG"
    },
    {
     "expr": "stddev_over_time(similarity_search_latency_gauge[1m])",
     "legendFormat": "STD"
    },
    {
     "expr": "stddev_over_time(similarity_search_latency_gauge[1m]) / (sqrt(count_over_time(similarity_search_latency_count[1m])))",
     "legendFormat": "SEM"
    }
   ]
  },
  {
   "title": "Min Semantic Search Latency(sec)-Milvus",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "logmin" ] } },
   "targets": [
    {
     "expr": "similarity_search_latency_gauge",
     "legendFormat": "Average Cosine Similarity"
    }
   ]
  },
  {
   "title": "Max Semantic Search Latency(sec)-Milvus",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "similarity_search_latency_gauge",
     "legendFormat": "Average Cosine Similarity"
    }
   ]
  }
 ]
}